# Generated by Django 4.2.5 on 2024-02-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aggregation", "0008_aggregationdevice_timestamp_offset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aggregationdevice",
            name="calculation_end_offset",
            field=models.FloatField(
                default=0,
                help_text="Offset in seconds used for the calculation end date. If negative, the calculation will start in the past; if positive, it will start in the future.",
            ),
        ),
        migrations.AlterField(
            model_name="aggregationdevice",
            name="calculation_start_offset",
            field=models.FloatField(
                default=0,
                help_text="Offset in seconds used for the calculation start date. If negative, the calculation will start in the past; if positive, it will start in the future.",
            ),
        ),
        migrations.AlterField(
            model_name="aggregationdevice",
            name="calculation_wait_offset",
            field=models.FloatField(
                default=0,
                help_text="Offset in seconds used to wait a certain amount of time before performing aggregation. Example: a value of 3600 will result in waiting before aggregating the last hour's data.",
            ),
        ),
        migrations.AlterField(
            model_name="aggregationdevice",
            name="timestamp_offset",
            field=models.FloatField(
                default=0,
                help_text="Offset in seconds used to save the aggregated value from the period start. If negative, the saved data will be in the past; if positive, it will be in the future.",
            ),
        ),
    ]
