# Generated by Django 4.2.5 on 2024-01-12 16:21

from django.db import migrations, models
import django.db.models.deletion
import pyscada.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pyscada", "0107_alter_calculatedvariableselector_period_fields"),
        ("operations", "0001_add_device_protocol"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationsVariable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "second_operation",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Examples in the <a href='https://github.com/clavay/PyScada-Operations'>readme</a>.",
                        max_length=400,
                    ),
                ),
                (
                    "operations_variable",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pyscada.variable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperationsDevice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "master_operation",
                    models.CharField(
                        default="",
                        help_text="Examples in the <a href='https://github.com/clavay/PyScada-Operations'>readme</a>.",
                        max_length=400,
                    ),
                ),
                (
                    "synchronisation",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "calendar"), (1, "trigger")], default=0
                    ),
                ),
                (
                    "start_from",
                    models.DateTimeField(
                        default=pyscada.models.start_from_default,
                        help_text="Calculate from this DateTime and then each period_factor*period",
                    ),
                ),
                (
                    "period",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "second"),
                            (1, "minute"),
                            (2, "hour"),
                            (3, "day"),
                            (4, "week"),
                            (5, "month"),
                            (6, "year"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "period_factor",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Example: set to 2 and choose minute to have a 2 minutes period",
                        validators=[pyscada.models.validate_nonzero],
                    ),
                ),
                (
                    "operations_device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="pyscada.device"
                    ),
                ),
                (
                    "trigger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pyscada.variable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperationsDataSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datasource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pyscada.datasource",
                    ),
                ),
            ],
        ),
    ]
