# Generated by Django 4.2.5 on 2024-01-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0004_periodicfield_aggregatedvariable_aggregateddevice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aggregatedvariable",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
